version: '3.1'

services:
  

  wordpress:
    image: wordpress:6.1.1-fpm-alpine
    depends_on:
      - db
    #command: bash -c "echo 'ServerName 127.0.0.1' >> /etc/apache2/apache2.conf"  
    restart: unless-stopped
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
    #  - ./apache2:/etc/apache2/  
    networks:
      -  frontend
      -  backend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      -  backend

  proxy:
    image: nginx:latest
    depends_on:
      - wordpress
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      -  frontend
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx:/etc/nginx/conf.d
     

  
volumes:
  db:    
  wordpress_data:
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

