---
- hosts: webserver
  become: yes
  vars:
    name_domain: nginxtsm
    path_certificate: /opt/cert/
  tasks:
    - name: install nginx (Task 1)
      apt:
        name: nginx
    - name: add config file (Task 2)
      template: 
        src: default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
    - name: create folder for certificate
      file:
        path: /opt/cert
        mode: 0775
        state: directory 
    - name: create private key
      community.crypto.openssl_privatekey:
        path: '{{ path_certificate }}certificate.key'
        size: 2048
        mode: 0600
        type: RSA      
    - name: add self-signed (Task 3) 
      community.crypto.x509_certificate:
        path: '{{ path_certificate }}certificate.crt'
        privatekey_path: '{{ path_certificate }}certificate.key'
        provider: selfsigned
    - name: start nginx
      service:
        name: nginx
        state: started
